### ISSUE TITLE
ConfigClientApplication cannot be started.

### ISSUE THREAD

**Issue by RobWin** [resilience4j/resilience4j-spring-cloud2-demo#1]
```
The bean 'bulkheadRegistry', defined in class path resource [io/github/resilience4j/bulkhead/configure/BulkheadConfiguration.class], could not be registered. A bean with that name has already been defined in class path
```

@dlsrb6342 Would you like to have a look at it?

I updated the version to 1.0.0-SNAPSHOT and sourceCompatibility to Java 8.

**Comment by dlsrb6342** [comment]
Ok I'll check it.

**Comment by RobWin** [comment]
Further when I use a config which defines `recordExceptions`, we get:

```
Binding to target [Bindable@7f608e21 type = java.lang.Class<java.lang.Throwable>[], value = 'provided', annotations = array<Annotation>[@io.github.resilience4j.core.lang.Nullable()]] failed:

    Property: resilience4j.circuitbreaker.configs.default.recordexceptions[2]
    Value: 
    Origin: "resilience4j.circuitbreaker.configs.default.recordExceptions[2]" from property source "bootstrapProperties"
    Reason: The elements [resilience4j.circuitbreaker.configs.default.recordexceptions[2]] were left unbound.
```
